
# docker run -d --name prometheus -h prometheus --dns 172.17.0.1 -p 9090:9090 $REGISTRY/tldr/prometheus
prometheus:
  dns: 172.17.0.1
  image: ${REGISTRY}/tldr/prometheus
  ports:
    - 9090:9090

# docker run -d --name promdash -h promdash --dns 172.17.0.1 -p 3000:3000 $REGISTRY/tldr/promdash
promdash:
  dns: 172.17.0.1
  image: ${REGISTRY}/tldr/promdash
  ports:
    - 3000:3000